# Site wide configuration

title: Oscar Branson
description: "Research, Travel, Thoughts"
logo: # 120x120 px default image used for Twitter summary card
teaser: defaut_teaser.jpg # 400x250 px default teaser image used in image archive grid
locale:
# url: http://0.0.0.0:4000
url: http://oscarbranson.github.io


# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: "Oscar Branson"
  email: "oscarbranson@gmail.com"
  twitter: "oscarbranson"
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: "oscarbranson"

# Add Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-62482404-1'
# http://jekyllbootstrap.com/usage/blog-configuration.html

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
